version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nextAiDB
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27013:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: